engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      react/require-default-props:
        enabled: false
    config:
      ignore_warnings: true
      config: .eslintrc
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.scss"

exclude_paths:
- src/assets/fonts/**/*