name: CI

on: 
  push:
    branches: 
      - develop

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "8.12.x"
      - run: yarn install
      - run: yarn deploy
